# Generated by Django 6.0.3 on 2026-03-30 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dialogueturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_value', models.FloatField()),
                ('sender', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='users.negotiationsession')),
            ],
        ),
    ]
