# Generated by Django 6.0.3 on 2026-04-05 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_update_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negotiationsession',
            name='updated_at',
        ),
    ]
