# Generated by Django 6.0.3 on 2026-04-06 00:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_negotiationsession_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dialogueturn',
            index=models.Index(fields=['session'], name='users_dialo_session_573526_idx'),
        ),
        migrations.AddIndex(
            model_name='dialogueturn',
            index=models.Index(fields=['turn_number'], name='users_dialo_turn_nu_da76ac_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiationsession',
            index=models.Index(fields=['user'], name='users_negot_user_id_25cc64_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiationsession',
            index=models.Index(fields=['status'], name='users_negot_status_edeb7e_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiationsession',
            index=models.Index(fields=['created_at'], name='users_negot_created_f9846b_idx'),
        ),
        migrations.AddIndex(
            model_name='offerhistory',
            index=models.Index(fields=['session'], name='users_offer_session_d6da55_idx'),
        ),
        migrations.AddIndex(
            model_name='offerhistory',
            index=models.Index(fields=['turn_number'], name='users_offer_turn_nu_b17f18_idx'),
        ),
    ]
