# Generated by Django 4.2.29 on 2026-04-06 04:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('education_level', models.CharField(max_length=30)),
                ('negotiation_experience', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NegotiationSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_reservation_price', models.FloatField()),
                ('initial_offer', models.FloatField()),
                ('final_offer', models.FloatField(blank=True, null=True)),
                ('final_price', models.FloatField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Abandoned', 'Abandoned')], max_length=20, null=True)),
                ('human_profit', models.FloatField(default=0)),
                ('ai_profit', models.FloatField(default=0)),
                ('turn_count', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users_api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DialogueTurn',
            fields=[
                ('turn_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_number', models.PositiveSmallIntegerField()),
                ('speaker', models.CharField(choices=[('Human', 'Human'), ('AI', 'AI')], max_length=10)),
                ('message', models.TextField(max_length=2000)),
                ('extracted_offer', models.FloatField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_turns', to='users_api.negotiationsession')),
            ],
            options={
                'ordering': ['turn_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferHistory',
            fields=[
                ('offer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_number', models.PositiveSmallIntegerField()),
                ('offer_amount', models.FloatField()),
                ('speaker', models.CharField(choices=[('Human', 'Human'), ('AI', 'AI')], max_length=10)),
                ('concession_amount', models.FloatField(blank=True, null=True)),
                ('concession_percentage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_history', to='users_api.negotiationsession')),
            ],
            options={
                'ordering': ['turn_number', 'created_at'],
                'indexes': [models.Index(fields=['session', 'turn_number'], name='users_api_o_session_d53234_idx')],
            },
        ),
    ]
