# Generated by Django 4.2.29 on 2026-04-06 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_userprofile_location_userprofile_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogueturn',
            name='concession_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialogueturn',
            name='is_counter_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dialogueturn',
            name='message_length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dialogueturn',
            name='offer_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialogueturn',
            name='offer_made',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dialogueturn',
            name='response_time_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialogueturn',
            name='sentiment',
            field=models.CharField(blank=True, default='neutral', max_length=10),
        ),
        migrations.AddField(
            model_name='dialogueturn',
            name='strategy_tag',
            field=models.CharField(blank=True, default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='dialogueturn',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='negotiationsession',
            name='dropoff_stage',
            field=models.CharField(blank=True, choices=[('before_offer', 'before_offer'), ('mid_negotiation', 'mid_negotiation'), ('after_offer', 'after_offer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='negotiationsession',
            name='session_status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed'), ('abandoned', 'abandoned'), ('timeout', 'timeout')], default='in_progress', max_length=20),
        ),
    ]
