# Generated by ChatGPT on 2026-04-08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_api", "0003_dialogueturn_concession_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSessionToken",
            fields=[
                ("token_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("token_prefix", models.CharField(db_index=True, max_length=16)),
                ("token_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="session_tokens", to="users_api.userprofile"),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["user", "expires_at"], name="users_api_us_user_id_0265b8_idx")],
            },
        ),
    ]
