# Generated by Django 4.2.29 on 2026-04-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_usersessiontoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersessiontoken',
            new_name='users_api_u_user_id_0f0f89_idx',
            old_name='users_api_us_user_id_0265b8_idx',
        ),
    ]
