# Generated by Django 4.2.29 on 2026-04-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0005_rename_users_api_us_user_id_0265b8_idx_users_api_u_user_id_0f0f89_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
