# Generated by Django 4.2.29 on 2026-04-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0006_userprofile_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='native_language',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
